export const ENGINE_PHYSICS_DEFAULTS = {
  runnerFps: 120,
  maxSubsteps: 3,
  positionIterations: 10,
  velocityIterations: 8,
  constraintIterations: 4,
}

export const DEFAULT_PHYSICS_CONFIG = {
  gravityY: 1.05,
  maxBallSpeed: 15,
  ballRadius: 12,
  ballDensity: 0.0022,
  ballFriction: 0.012,
  ballFrictionAir: 0.004,
  ballRestitution: 0.7,
  bumperRestitution: 0.95,
  wallRestitution: 0.55,
  bumperImpulse: 0.018,
  bumperGoalBias: 0.2,
  bumperWeakHitBoost: 1.35,
  bumperVelocityKick: 1.15,
  bumperLowSpeedThreshold: 7,
  bumperHitScale: 0.14,
  bumperHitDurationMs: 90,
  playerImpulse: 0.014,
  playerWeakHitBoost: 0.9,
  playerVelocityKick: 0.8,
  playerLowSpeedThreshold: 7,
  playerHitOffsetPx: 6,
  playerHitDurationMs: 110,
  goalkeeperImpulse: 0.016,
  goalkeeperWeakHitBoost: 1.1,
  goalkeeperVelocityKick: 1,
  goalkeeperLowSpeedThreshold: 8,
  goalkeeperGoalAvoidBias: 0.35,
  goalkeeperHitOffsetPx: 8,
  goalkeeperHitDurationMs: 120,
  flipperSpeed: 0.1,
  flipperKick: 0.023,
  flipperGoalBias: 0.2,
  goalkeeperSpeed: 63,
  wallPadding: 6,
  goalPadding: 4,
  playerPadding: 0,
  bumperPadding: 0,
  flipperPadding: 0,
  showVisualShapes: true,
  showMatterBodies: false,
  showSafetyBodies: false,
  showAlignmentCompare: false,
  freezePhysics: false,
  launchForceMin: 0.035,
  launchForceMax: 0.05,
  launchDelayMs: 300,
  launchXMin: -0.5,
  launchXMax: 0.5,
  launchXDeadZone: 0.06,
}

export function createDefaultParams() {
  return { ...DEFAULT_PHYSICS_CONFIG }
}
